//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XMLDemo.XMLWriterService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org/Webservices", ConfigurationName="XMLWriterService.XMLFileWriterSoap")]
    public interface XMLFileWriterSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/Webservices is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Webservices/HelloWorld", ReplyAction="*")]
        XMLDemo.XMLWriterService.HelloWorldResponse HelloWorld(XMLDemo.XMLWriterService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Webservices/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<XMLDemo.XMLWriterService.HelloWorldResponse> HelloWorldAsync(XMLDemo.XMLWriterService.HelloWorldRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/Webservices", Order=0)]
        public XMLDemo.XMLWriterService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(XMLDemo.XMLWriterService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/Webservices", Order=0)]
        public XMLDemo.XMLWriterService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(XMLDemo.XMLWriterService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/Webservices")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface XMLFileWriterSoapChannel : XMLDemo.XMLWriterService.XMLFileWriterSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class XMLFileWriterSoapClient : System.ServiceModel.ClientBase<XMLDemo.XMLWriterService.XMLFileWriterSoap>, XMLDemo.XMLWriterService.XMLFileWriterSoap {
        
        public XMLFileWriterSoapClient() {
        }
        
        public XMLFileWriterSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public XMLFileWriterSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XMLFileWriterSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XMLFileWriterSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        XMLDemo.XMLWriterService.HelloWorldResponse XMLDemo.XMLWriterService.XMLFileWriterSoap.HelloWorld(XMLDemo.XMLWriterService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            XMLDemo.XMLWriterService.HelloWorldRequest inValue = new XMLDemo.XMLWriterService.HelloWorldRequest();
            inValue.Body = new XMLDemo.XMLWriterService.HelloWorldRequestBody();
            XMLDemo.XMLWriterService.HelloWorldResponse retVal = ((XMLDemo.XMLWriterService.XMLFileWriterSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XMLDemo.XMLWriterService.HelloWorldResponse> XMLDemo.XMLWriterService.XMLFileWriterSoap.HelloWorldAsync(XMLDemo.XMLWriterService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<XMLDemo.XMLWriterService.HelloWorldResponse> HelloWorldAsync() {
            XMLDemo.XMLWriterService.HelloWorldRequest inValue = new XMLDemo.XMLWriterService.HelloWorldRequest();
            inValue.Body = new XMLDemo.XMLWriterService.HelloWorldRequestBody();
            return ((XMLDemo.XMLWriterService.XMLFileWriterSoap)(this)).HelloWorldAsync(inValue);
        }
    }
}
